sudo: required
services:
  - docker

before_install:
  - docker build -t mokjunneng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mokjunneng/react-test npm test -- --coverage

after_success:
  - docker build -t mokjunneng/multi-client ./client
  - docker build -t mokjunneng/multi-nginx ./nginx
  - docker build -t mokjunneng/multi-server ./server
  - docker build -t mokjunneng/multi-worker ./worker
